version: '3.7'
 
services:
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./data/searxng:/etc/searxng
    environment:
      - TZ=America/Chicago
    ports:
      - 8880:8080
    restart: always