version: "3"

services:
  mariadb:
    image: mariadb
    container_name: lexi-studio-db
    restart: unless-stopped
    ports:
      - 5506:3306
    volumes:
      -  ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}